# -*- coding: utf-8 -*-

import importlib
import importlib.util
import os
import setuptools

"""This file is used to package the AttachmentCarousel plugin.

- It was generated by the InvenTree Plugin Creator tool - version 1.7.0
- Ref: https://github.com/inventree/plugin_creator
"""

"""Read the plugin version from the source code."""
module_path = os.path.join(os.path.dirname(__file__), "attachment_carousel", "__init__.py")
spec = importlib.util.spec_from_file_location("attachment_carousel", module_path)
attachment_carousel = importlib.util.module_from_spec(spec)
spec.loader.exec_module(attachment_carousel)

with open('README.md', encoding='utf-8') as f:
    long_description = f.read()

setuptools.setup(
    name="inventree-attachment-carousel",
    version=attachment_carousel.PLUGIN_VERSION,
    author="Jason Huang",
    author_email="email@admin.org",
    description="An example part pnanel plugin that displays image attachments in a carousel",
    long_description=long_description,
    long_description_content_type='text/markdown',
    url="https://my-project-url.com",
    license="MIT",
    packages=setuptools.find_packages(),
    keywords="inventree plugin",
    include_package_data=True,
    install_requires=[
        # Enter your plugin library dependencies here
    ],
    setup_requires=[
        "wheel",
        "twine",
    ],
    python_requires=">=3.9",
    entry_points={
        "inventree_plugins": [
            "AttachmentCarousel = attachment_carousel.core:AttachmentCarousel"
        ]
    },
)
